#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-wireguard-update event
#--------------------------------------------------

my $event = "nethserver-wireguard-update";

event_actions($event, 
    'initialize-default-databases' => '00',
    'nethserver-wireguard-conf' => '02',
    'runlevel-adjust' => '70',
    'firewall-adjust' => '80'
);

event_templates($event, 
    '/etc/sysctl.d/wireguard.conf',
    '/etc/shorewall/zones',
    '/etc/shorewall/interfaces',
    '/etc/shorewall/rules',
    '/etc/shorewall/policy'
);

event_services($event, 
    'wg-quick@' => 'restart',
    'shorewall' => 'reload'
);

