#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-postgresql-update event
#--------------------------------------------------

my $event = "nethserver-zammad-update";

event_actions($event, 
    'initialize-default-databases' => '00',
    'nethserver-wireguard-conf' => '02' #must be executed before template expansion
);
event_templates($event, 
    '/etc/wireguard/server.conf',
    '/etc/sysctl.d/wireguard.conf'
);

event_services($event, 
    'wg-quick@wg0' => 'restart'
#    'httpd' => 'restart',
#    'zammad' => 'restart',
#    'elasticsearch' => 'restart',
#    'postgresql' => 'restart'
);

#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

#$event = 'pre-backup-data';

#event_actions($event, 'nethserver-zammad-backup' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

#$event = 'post-restore-data';

#event_actions($event, 'nethserver-zammad-restore' => 50);

#event_services($event, 'zammad' => 'restart');
