#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-wireguard-update event
#--------------------------------------------------

my $event = "nethserver-wireguard-update";

event_actions($event, 
    'initialize-default-databases' => '00',
    'nethserver-wireguard-conf' => '02'
);

event_templates($event, 
    '/etc/sysctl.d/wireguard.conf',
    '/etc/shorewall/zones',
    '/etc/shorewall/interfaces',
    '/etc/shorewall/rules',
    '/etc/shorewall/policy',
    '/etc/httpd/conf.d/zz_wireguard.conf',
    '/etc/systemd/system/wg-manager.service'
);

event_services($event, 
    'httpd' => 'reload',
    'shorewall' => 'reload'
);

