#!/usr/bin/bash

# Prepare python environment and install requirements and gunicorn
if [ ! -d /opt/wg-manager/venv ]; then
  cd /opt/wg-manager
  su wg-manager -c "/opt/rh/rh-python38/root/usr/bin/python3.8 -m venv venv && source venv/bin/activate && pip3 install --upgrade pip && pip3 install -r requirements.txt && pip3 install gunicorn"
fi
